name: Olá Mundo!
on: [push]
jobs:
  ola_mundo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        - name: Ola, Mundo!
          run: echo "Olá, Mundo!"